version: '3'

services:
    mysql:
        image: mariadb
        container_name: mysql-container
        expose:
            - 3306
        ports:
            - '3306:3306'
        volumes:
            - ./db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: username
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: wordpress
        restart: always
        networks:
            - wordpress-network
            
    php-cli:
        build: ./php-cli/
        container_name: php-container
        expose:
            - 9000
        ports:
            - '9000:9000'
        volumes:
            - ./www/html/:/var/www/html/ 
        networks:
            - wordpress-network

    nginx:
        build: ./nginx/
        container_name: nginx-container
        ports:
            - '80:80'
        volumes:
            - ./logs/nginx:/var/log/nginx
            - ./www/html/:/var/www/html/ 
        networks:
            - wordpress-network
networks:
    wordpress-network: